### ISSUE TITLE
Should we use English as main application language?

### ISSUE THREAD

**Issue by Ibrahimsyah** [Ibrahimsyah/next-ts#9]
Since this is an open source project, where people around the globe can access and contribute. What do you think if we change the main application language to English? so people who are seeing this repo understand what we are working on

**Comment by 0xMulyadiKabel** [comment]
agree sir,  I think that's a great idea

**Comment by Ibrahimsyah** [comment]
> agree sir, I think that's a great idea

Thank you, it looks better now
